export const DEFAULT_CLIENT_ID = '1505505092214980608';

export const PROFILES = {
  claude: {
    binEnv: 'CLAUDE_BIN',
    bin: 'claude',
    name: 'Claude Code',
    state: 'Using Claude Code',
    modelEnv: 'CLAUDE_MODEL',
    modelEnvs: ['CLAUDE_MODEL', 'ANTHROPIC_MODEL', 'ANTHROPIC_DEFAULT_OPUS_MODEL', 'ANTHROPIC_DEFAULT_SONNET_MODEL', 'ANTHROPIC_DEFAULT_HAIKU_MODEL'],
    largeImage: 'claude',
    smallImage: 'terminal',
  },
  codex: {
    binEnv: 'CODEX_BIN',
    bin: 'codex',
    name: 'Codex CLI',
    state: 'Using Codex CLI',
    modelEnv: 'OPENAI_MODEL',
    modelEnvs: ['OPENAI_MODEL', 'CODEX_MODEL'],
    largeImage: 'codex',
    smallImage: 'terminal',
  },
  gemini: {
    binEnv: 'GEMINI_BIN',
    bin: 'gemini',
    name: 'Gemini CLI',
    state: 'Using Gemini CLI',
    modelEnv: 'GEMINI_MODEL',
    modelEnvs: ['GEMINI_MODEL'],
    largeImage: 'gemini',
    smallImage: 'terminal',
  },
  cursor: {
    binEnv: 'CURSOR_AGENT_BIN',
    bin: 'cursor-agent',
    name: 'Cursor Agent',
    state: 'Using Cursor Agent',
    largeImage: 'cursor',
    smallImage: 'terminal',
  },
  opencode: {
    binEnv: 'OPENCODE_BIN',
    bin: 'opencode',
    name: 'opencode',
    state: 'Using opencode',
    modelEnv: 'OPENCODE_MODEL',
    modelEnvs: ['OPENCODE_MODEL'],
    largeImage: 'opencode',
    smallImage: 'terminal',
  },
  custom: {
    binEnv: 'PRESENCE_BIN',
    bin: 'node',
    name: 'CLI',
    state: 'Using CLI',
    largeImage: 'terminal',
    smallImage: 'terminal',
  },
};
